#ifndef TENSORFLOW_LITE_MICRO_EXAMPLES_MICRO_SPEECH_INDUSTRIAL_SAMPLE_DATA_H_
#define TENSORFLOW_LITE_MICRO_EXAMPLES_MICRO_SPEECH_INDUSTRIAL_SAMPLE_DATA_H_

#include <cstdint>

extern const int g_industrial_sample_data_size;
extern const int16_t g_industrial_sample_data[];

#endif  // TENSORFLOW_LITE_MICRO_EXAMPLES_MICRO_SPEECH_YES_1000MS_SAMPLE_DATA_H_
